---
title: "00-larval-size"
author: "Laura Spencer"
date: "2022-11-08"
output: html_document
---


```{r include = FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = F, message = F)
```

```{r, message=FALSE, warning=FALSE, results=FALSE}
#### Load libraries and source scripts 

source("../references/biostats.R")

# Add all required libraries that are installed with install.packages() here
list.of.packages <- c("RCurl", "tidyverse", "vegan", "pheatmap", "pastecs", "factoextra", "FactoMineR", "RColorBrewer", "tibble", "reshape2", "plotly", "cowplot", "clipr", "janitor", "ggpubr", "forcats", "apeglm", "car", "vsn", "devtools", "grid", "gridGraphics", "Rfast", "dendextend", "RColorBrewer", "scales", "VennDiagram")

# Add all libraries that are installed using BiocManager here
bioconductor.packages <- c("DESeq2", "WGCNA")

# # Install BiocManager if needed
# if(!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
# 
# # Get names of all required packages that aren't installed
# new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
# new.bioc.packages <- bioconductor.packages[!(bioconductor.packages %in% installed.packages()[, "Package"])]
# # Install all new packages
# if(length(new.packages)) install.packages(new.packages)
# if(length(new.bioc.packages)) BiocManager::install(new.bioc.packages)

# Load all required libraries
all.packages <- c(list.of.packages, bioconductor.packages)
lapply(all.packages, FUN = function(X) {
  do.call("require", list(X))
})


# Github packages 
install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
library(pairwiseAdonis)
```

```{r}
pcod <- read_csv("../data/size_data_raw.csv") %>%
  clean_names() %>%
  mutate_at(c("temperature_treatment", "days_post_hatch", "measurement", "tank", "photo_number"), factor) %>%
  mutate(date_collected=as.Date(date_collected, "%m/%d/%Y")) %>% 
  #filter(measurement=="Length") %>%
  left_join(
    read_csv("../data/sample_data.csv") %>%
  clean_names() %>%
  mutate_at(c("sample_date", "tank", "photo_number", "treatment", "temperature", "p_h"), factor) %>%
    mutate(date_collected=as.Date(sample_date, "%m/%d/%Y")) %>% 
    dplyr::select(date_collected, tank, temperature, p_h, photo_number, vial), 
  by=c("date_collected", "tank", "photo_number"))

pcod %>% View() #write_clip()
```

```{r}
# Define x limits 
min((pcod %>% filter(measurement=="Length"))$value_mm)
max((pcod %>% filter(measurement=="Length"))$value_mm)

# Examine stage-specific length data by temperature and pH 
pcod %>% filter(measurement=="Length") %>% 
  ggplot(aes(x=value_mm, fill=p_h)) + geom_histogram(bins = 35, alpha=0.5, position="dodge") + 
  xlim(4.5, 8) + scale_x_continuous(breaks=seq(4.5,8, 0.5)) + 
  facet_wrap(~temperature, nrow=3) + theme_minimal() + 
  ggtitle("Length") + 
  scale_fill_manual(values=c("blue", "red"))

# Examine stage-specific length data by temperature and pH 
pcod %>% filter(measurement=="Height") %>% 
  ggplot(aes(x=value_mm, fill=p_h)) + geom_histogram(bins = 35, alpha=0.5, position="dodge") + 
  xlim(4.5, 8) + scale_x_continuous(breaks=seq(4.5,8, 0.5)) + 
  facet_wrap(~temperature, nrow=3) + theme_minimal() + 
  ggtitle("Height") + 
  scale_fill_manual(values=c("blue", "red"))
```
```{r}
# Examine stage-specific length data by temperature and pH 
pcod %>% filter(measurement=="Length") %>% 
  mutate(p_h=as.factor(case_when(p_h=="amb" ~ "Ambient pCO2", TRUE ~ "High pCO2"))) %>%
  ggplot(aes(x=temperature , y=value_mm, color=temperature)) + 
  geom_boxplot() +
  geom_point(size=2, position=position_jitter(w = 0.15,h = 0)) +
  theme_bw() + 
  ggtitle("Length") + xlab("Temperature") + ylab("Length") +
  scale_color_manual(name="Temperature", 
                    values=c("3"= "navyblue", "6"="darkgreen", "10"="firebrick4")) + 
  facet_wrap(~p_h)

# Examine stage-specific height data by temperature and pH 
pcod %>% filter(measurement=="Height") %>% 
  mutate(p_h=as.factor(case_when(p_h=="amb" ~ "Ambient pCO2", TRUE ~ "High pCO2"))) %>%
  ggplot(aes(x=temperature , y=value_mm, color=temperature)) + 
  geom_boxplot() +
  geom_point(size=2, position=position_jitter(w = 0.15,h = 0)) +
  theme_bw() + 
  ggtitle("Height") + xlab("Temperature") + ylab("Height") +
  scale_color_manual(name="Temperature", 
                    values=c("3"= "navyblue", "6"="darkgreen", "10"="firebrick4")) + 
  facet_wrap(~p_h)

# Examine stage-specific height/length by temperature and pH 
pcod %>%
  pivot_wider(names_from = "measurement", values_from = "value_mm") %>%
  filter(file!="Pcod_OA_051622_3.2x_T17_rep0002.tif") %>%
  mutate(p_h=as.factor(case_when(p_h=="amb" ~ "Ambient pCO2", TRUE ~ "High pCO2"))) %>%
  ggplot(aes(x=temperature , y=Height/Length, color=temperature)) + 
  geom_boxplot() +
  geom_point(size=2, position=position_jitter(w = 0.15,h = 0)) +
  theme_bw() + 
  ggtitle("Height/Length") + xlab("Temperature") + ylab("Height/Length") +
  scale_color_manual(name="Temperature", 
                    values=c("3"= "navyblue", "6"="darkgreen", "10"="firebrick4")) + 
  facet_wrap(~p_h)

```

```{r}
# Examine distribution of height/length ratio
pcod%>%pivot_wider(names_from = "measurement", values_from = "value_mm") %>%
  ggplot(aes(x=Height/Length)) + geom_histogram(color="black", fill="white") #one outlier, "Pcod_OA_051622_3.2x_T17_rep0002.tif"

ratio <- pcod%>%pivot_wider(names_from = "measurement", values_from = "value_mm") %>% 
  filter(file!="Pcod_OA_051622_3.2x_T17_rep0002.tif") %>%
  mutate(ratio=Height/Length)

shapiro.test(ratio$ratio) #fairly normally distributed 

# Effect of treatment on height/length ratio? 
summary(aov(Height/Length ~ temperature*p_h, ratio))
(CI.tukey <- TukeyHSD(aov(Height/Length ~ temperature*p_h, ratio)))

# Which treatments differ in their ratio of height / length? 
CI.tukey$`temperature:p_h` %>% as.data.frame() %>% clean_names() %>% filter(p_adj<0.05)

# 6C-Ambient pH reared fish have larger height/length (i.e. are "fatter") than all other treatments except for 3-Ambient. 

ggplot(ratio, aes(x=Length, y=Height)) + geom_point(aes(color=interaction(temperature,p_h))) + theme_minimal() + 
  geom_smooth(method = "lm", color="gray50") +
  scale_color_manual(values=c("3.amb"= "navyblue", "3.low"="royalblue1","6.amb"="darkgreen",
                              "6.low"="yellow3","10.amb"="firebrick4", "10.low"="sienna2"))

# How many samples per treatment in this data?
ratio %>% group_by(temperature, p_h) %>% tally()
```
```{r}
# Effect of treatment on height? 
summary(aov(value_mm ~ temperature*p_h, pcod[pcod$measurement=="Height",]))
TukeyHSD(aov(value_mm ~ temperature*p_h, pcod[pcod$measurement=="Height",]))
```

```{r}
pcod %>% 
  group_by(temperature, p_h, measurement) %>%
  summarise(mean=mean(value_mm, na.rm = T), sd=sd(value_mm, na.rm = T), min=min(value_mm), max=max(value_mm)) %>% 
  arrange(measurement, temperature, p_h)

write_csv(pcod, file="../data/size_data_annotated.csv", col_names = TRUE)

# For some reason 5/16 dates are duplicated - why?
pcod %>% filter(measurement=="Length") %>% filter(date_collected == "5/16/22") %>% 
  write_clip()
```

Rerun height/length analysis on just fish used in RNASeq analysis 

```{r}
#load(file="../data/sample.info")

(ratio.rnaseq <- pcod%>%pivot_wider(names_from = "measurement", values_from = "value_mm") %>% 
  filter(file!="Pcod_OA_051622_3.2x_T17_rep0002.tif") %>%
  mutate(ratio=Height/Length) %>% 
  filter(file %in% sample.info$photo_file))


# Examine stage-specific height/length by temperature and pH 
ratio.rnaseq %>%
  ggplot(aes(x=temperature , y=ratio, fill=p_h)) + 
  #geom_violin() + 
  geom_boxplot() +
  theme_minimal() + 
  ggtitle("Height/Length") + xlab("Temperature") + ylab("Height") +
  scale_fill_manual(values=c("blue", "red"))

# Examine distribution of height/length ratio
ratio.rnaseq %>%
  ggplot(aes(x=ratio)) + geom_histogram(color="black", fill="white")

shapiro.test(ratio.rnaseq$ratio) #normally distributed 

# Effect of treatment on height/length ratio? 
summary(aov(ratio ~ temperature*p_h, ratio.rnaseq)) #no effect
(CI.tukey <- TukeyHSD(aov(ratio ~ temperature*p_h, ratio.rnaseq))) 
```


```{r}
## read in and plot sizes selected for RNAseq 
read_csv("../data/length_data_rnaseq.csv", na = c("NA", "")) %>%
  clean_names() %>%
  mutate_at(c("temperature", "p_h", "tank"), factor) %>% 
  ggplot(aes(x=value_mm, color=p_h, fill=p_h)) + geom_histogram(bins = 25, alpha=0.5, position="dodge") + 
  #xlim(4.5, 8) + 
  scale_x_continuous(breaks=seq(4.5,8, 0.5)) + 
  facet_wrap(~temperature, nrow=3) + theme_minimal() + 
  ggtitle("RNA-Seq Samples - size spectrum")

```


